name: release
permissions:
  contents: write
on:
  workflow_dispatch:
    inputs:
      bump:
        type: choice
        description: Version Bump
        options:
          - patch
          - minor
          - major
env:
  PACKAGE_NAME: example-device-app
jobs:
  release:
    name: Package and release
    runs-on: ubuntu-latest
    environment:
      name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set version
        run: |
          set -euxo pipefail
          NEXT_VERSION=$(./ci/tag.sh "${{ inputs.bump }}" | tail -n1)
          echo "RELEASE_VERSION=${NEXT_VERSION}" >> $GITHUB_ENV
      - name: Package
        run: ./ci/build.sh
        env:
          SEMVER: ${{ env.RELEASE_VERSION }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: dist/*

      - name: Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          generate_release_notes: true
          name: ${{ env.RELEASE_VERSION }}
          tag_name: ${{ env.RELEASE_VERSION }}
          draft: true
          files: |
            ./dist/*

      - name: Publish
        if: env.PUBLISH_TOKEN
        env:
          PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
          PUBLISH_REPO: ${{ secrets.PUBLISH_REPO }}
          PUBLISH_OWNER: ${{ secrets.PUBLISH_OWNER }}
        run: |
          ./ci/publish.sh ./dist --repo "$PUBLISH_REPO" --owner "$PUBLISH_OWNER"

      - uses: reubenmiller/setup-go-c8y-cli@main
        env:
          C8Y_BASEURL: '${{ secrets.C8Y_BASEURL }}'
          C8Y_USER: '${{ secrets.C8Y_USER }}'
          C8Y_PASSWORD: '${{ secrets.C8Y_PASSWORD }}'
        with:
          showVersion: true
          showTenant: true
      - name: publish
        env:
          C8Y_BASEURL: '${{ secrets.C8Y_BASEURL }}'
          C8Y_USER: '${{ secrets.C8Y_USER }}'
          C8Y_PASSWORD: '${{ secrets.C8Y_PASSWORD }}'
        run: |
          c8y software get --id "$PACKAGE_NAME" -n --silentStatusCodes 404 ||
            c8y software create -n --softwareType apt --name "$PACKAGE_NAME"

          # Only create reference to software/version, don't upload the package directly
          # as it will be accessible from cloudsmith
          c8y software versions create -n \
            --software "$PACKAGE_NAME" \
            --version "${{ env.RELEASE_VERSION }}" \
            --url " "
